In [21]:
import numpy as np

# 1 qubit 50 iterations

In [22]:
scores = np.array(
[[[0.56, 0.68, 0.76],
  [0.56, 0.68, 0.76],
  [0.56, 0.68, 0.76],
  [0.56, 0.68, 0.76],
  [0.56, 0.68, 0.76],
  [0.56, 0.68, 0.76],
  [0.56, 0.68, 0.76],
  [0.56, 0.68, 0.76],
  [0.56, 0.68, 0.76],
  [0.56, 0.68, 0.76],
  [0.56, 0.68, 0.76],
  [0.56, 0.68, 0.76],
  [0.56, 0.68, 0.76]],

 [[0.92, 0.76, 0.36],
  [0.84, 0.8, 0.6 ],
  [0.84, 0.72, 0.72],
  [0.84, 0.76, 0.8 ],
  [0.84, 0.72, 0.52],
  [0.92, 0.68, 0.36],
  [0.84, 0.68, 0.6 ],
  [0.88, 0.72, 0.56],
  [0.88, 0.8, 0.72],
  [0.84, 0.72, 0.56],
  [0.84, 0.72, 0.76],
  [0.84, 0.68, 0.32],
  [0.84, 0.8, 0.56]],

 [[0.92, 0.64, 0.76],
  [0.92, 0.72, 0.76],
  [0.92, 0.8, 0.76],
  [0.92, 0.76, 0.72],
  [0.92, 0.64, 0.76],
  [0.92, 0.8, 0.8 ],
  [0.92, 0.88, 0.72],
  [0.92, 0.84, 0.76],
  [0.92, 0.8, 0.8 ],
  [0.92, 0.48, 0.72],
  [0.92, 0.64, 0.8 ],
  [0.92, 0.88, 0.76],
  [0.92, 0.84, 0.72]]],
)

print(scores)

[[[0.56 0.68 0.76]
  [0.56 0.68 0.76]
  [0.56 0.68 0.76]
  [0.56 0.68 0.76]
  [0.56 0.68 0.76]
  [0.56 0.68 0.76]
  [0.56 0.68 0.76]
  [0.56 0.68 0.76]
  [0.56 0.68 0.76]
  [0.56 0.68 0.76]
  [0.56 0.68 0.76]
  [0.56 0.68 0.76]
  [0.56 0.68 0.76]]

 [[0.92 0.76 0.36]
  [0.84 0.8  0.6 ]
  [0.84 0.72 0.72]
  [0.84 0.76 0.8 ]
  [0.84 0.72 0.52]
  [0.92 0.68 0.36]
  [0.84 0.68 0.6 ]
  [0.88 0.72 0.56]
  [0.88 0.8  0.72]
  [0.84 0.72 0.56]
  [0.84 0.72 0.76]
  [0.84 0.68 0.32]
  [0.84 0.8  0.56]]

 [[0.92 0.64 0.76]
  [0.92 0.72 0.76]
  [0.92 0.8  0.76]
  [0.92 0.76 0.72]
  [0.92 0.64 0.76]
  [0.92 0.8  0.8 ]
  [0.92 0.88 0.72]
  [0.92 0.84 0.76]
  [0.92 0.8  0.8 ]
  [0.92 0.48 0.72]
  [0.92 0.64 0.8 ]
  [0.92 0.88 0.76]
  [0.92 0.84 0.72]]]


# 1 qubit 200 iterations

In [23]:
scores = np.array(
[[[0.96, 0.58, 0.8 ],
  [0.96, 0.58, 0.8 ],
  [0.96, 0.58, 0.8 ],
  [0.96, 0.58, 0.8 ],
  [0.96, 0.58, 0.8 ],
  [0.96, 0.58, 0.8 ],
  [0.96, 0.58, 0.8 ],
  [0.96, 0.58, 0.8 ],
  [0.96, 0.58, 0.8 ],
  [0.96, 0.58, 0.8 ],
  [0.96, 0.58, 0.8 ],
  [0.96, 0.58, 0.8 ],
  [0.96, 0.58, 0.8 ]],

 [[0.82, 0.76, 0.56],
  [0.84, 0.48, 0.48],
  [0.84, 0.62, 0.6 ],
  [0.84, 0.76, 0.44],
  [0.84, 0.72, 0.44],
  [0.92, 0.68, 0.72],
  [0.84, 0.68, 0.52],
  [0.88, 0.72, 0.44],
  [0.88, 0.78, 0.56],
  [0.84, 0.72, 0.52],
  [0.94, 0.62, 0.48],
  [0.84, 0.68, 0.6 ],
  [0.84, 0.78, 0.76]],

 [[0.82, 0.4, 0.84],
  [0.92, 0.2, 0.8 ],
  [0.92, 0.8, 0.8 ],
  [0.92, 0.96, 0.84],
  [0.82, 0.4, 0.8 ],
  [0.92, 0.48, 0.8 ],
  [0.82, 0.48, 0.84],
  [0.82, 0.4, 0.84],
  [0.92, 0.78, 0.84],
  [0.92, 0.8, 0.84],
  [0.82, 0.84, 0.84],
  [0.92, 0.88, 0.84],
  [0.92, 0.84, 0.84]]],
)

print(scores)

[[[0.96 0.58 0.8 ]
  [0.96 0.58 0.8 ]
  [0.96 0.58 0.8 ]
  [0.96 0.58 0.8 ]
  [0.96 0.58 0.8 ]
  [0.96 0.58 0.8 ]
  [0.96 0.58 0.8 ]
  [0.96 0.58 0.8 ]
  [0.96 0.58 0.8 ]
  [0.96 0.58 0.8 ]
  [0.96 0.58 0.8 ]
  [0.96 0.58 0.8 ]
  [0.96 0.58 0.8 ]]

 [[0.82 0.76 0.56]
  [0.84 0.48 0.48]
  [0.84 0.62 0.6 ]
  [0.84 0.76 0.44]
  [0.84 0.72 0.44]
  [0.92 0.68 0.72]
  [0.84 0.68 0.52]
  [0.88 0.72 0.44]
  [0.88 0.78 0.56]
  [0.84 0.72 0.52]
  [0.94 0.62 0.48]
  [0.84 0.68 0.6 ]
  [0.84 0.78 0.76]]

 [[0.82 0.4  0.84]
  [0.92 0.2  0.8 ]
  [0.92 0.8  0.8 ]
  [0.92 0.96 0.84]
  [0.82 0.4  0.8 ]
  [0.92 0.48 0.8 ]
  [0.82 0.48 0.84]
  [0.82 0.4  0.84]
  [0.92 0.78 0.84]
  [0.92 0.8  0.84]
  [0.82 0.84 0.84]
  [0.92 0.88 0.84]
  [0.92 0.84 0.84]]]


# 1 qubit 400 iterations

In [24]:
scores = np.array(
 [[[0.96, 0.8, 0.84],
  [0.96, 0.8, 0.84],
  [0.96, 0.8, 0.84],
  [0.96, 0.8, 0.84],
  [0.96, 0.8, 0.84],
  [0.96, 0.8, 0.84],
  [0.96, 0.8, 0.84],
  [0.96, 0.8, 0.84],
  [0.96, 0.8, 0.84],
  [0.96, 0.8, 0.84],
  [0.96, 0.8, 0.84],
  [0.96, 0.8, 0.84],
  [0.96, 0.8, 0.84]],

 [[0.92, 0.86, 0.84],
  [0.84, 0.78, 0.6 ],
  [0.94, 0.2, 0.52],
  [0.94, 0.86, 0.44],
  [0.74, 0.2, 0.48],
  [0.92, 0.8, 0.44],
  [0.94, 0.78, 0.6 ],
  [0.98, 0.92, 0.48],
  [0.88, 0.8, 0.44],
  [0.94, 0.72, 0.44],
  [0.94, 0.62, 0.8 ],
  [0.94, 0.8, 0.56],
  [0.84, 0.8, 0.84]],

 [[0.92, 0.4, 0.84],
  [0.82, 0.62, 0.84],
  [0.92, 0.8, 0.84],
  [0.92, 0.6, 0.84],
  [0.92, 0.94, 0.84],
  [0.92, 0.8, 0.84],
  [0.92, 0.88, 0.8 ],
  [0.92, 0.74, 0.84],
  [0.92, 0.78, 0.84],
  [0.92, 0.88, 0.8 ],
  [0.92, 0.64, 0.8 ],
  [0.92, 0.78, 0.84],
  [0.92, 0.84, 0.76]]],
)

print(scores)

[[[0.96 0.8  0.84]
  [0.96 0.8  0.84]
  [0.96 0.8  0.84]
  [0.96 0.8  0.84]
  [0.96 0.8  0.84]
  [0.96 0.8  0.84]
  [0.96 0.8  0.84]
  [0.96 0.8  0.84]
  [0.96 0.8  0.84]
  [0.96 0.8  0.84]
  [0.96 0.8  0.84]
  [0.96 0.8  0.84]
  [0.96 0.8  0.84]]

 [[0.92 0.86 0.84]
  [0.84 0.78 0.6 ]
  [0.94 0.2  0.52]
  [0.94 0.86 0.44]
  [0.74 0.2  0.48]
  [0.92 0.8  0.44]
  [0.94 0.78 0.6 ]
  [0.98 0.92 0.48]
  [0.88 0.8  0.44]
  [0.94 0.72 0.44]
  [0.94 0.62 0.8 ]
  [0.94 0.8  0.56]
  [0.84 0.8  0.84]]

 [[0.92 0.4  0.84]
  [0.82 0.62 0.84]
  [0.92 0.8  0.84]
  [0.92 0.6  0.84]
  [0.92 0.94 0.84]
  [0.92 0.8  0.84]
  [0.92 0.88 0.8 ]
  [0.92 0.74 0.84]
  [0.92 0.78 0.84]
  [0.92 0.88 0.8 ]
  [0.92 0.64 0.8 ]
  [0.92 0.78 0.84]
  [0.92 0.84 0.76]]]


# 2 qubit 50 iterations

In [25]:
scores = np.array(
[[[0.56, 0.68, 0.76],
  [0.56, 0.68, 0.76],
  [0.56, 0.68, 0.76],
  [0.56, 0.68, 0.76],
  [0.56, 0.68, 0.76],
  [0.56, 0.68, 0.76],
  [0.56, 0.68, 0.76],
  [0.56, 0.68, 0.76],
  [0.56, 0.68, 0.76],
  [0.56, 0.68, 0.76],
  [0.56, 0.68, 0.76],
  [0.56, 0.68, 0.76],
  [0.56, 0.68, 0.76]],

 [[0.92, 0.6, 0.36],
  [0.94, 0.8, 0.36],
  [0.94, 0.2, 0.32],
  [0.84, 0.56, 0.36],
  [0.94, 0.52, 0.32],
  [0.92, 0.48, 0.32],
  [0.94, 0.68, 0.32],
  [0.98, 0.52, 0.36],
  [0.98, 0.58, 0.32],
  [0.84, 0.62, 0.32],
  [0.84, 0.42, 0.28],
  [0.94, 0.68, 0.36],
  [0.94, 0.48, 0.32]],

 [[0.92, 0.34, 0.32],
  [0.92, 0.42, 0.32],
  [0.92, 0.38, 0.32],
  [0.92, 0.36, 0.4 ],
  [0.92, 0.34, 0.32],
  [0.92, 0.38, 0.32],
  [1., 0.42, 0.32],
  [0.88, 0.42, 0.32],
  [1., 0.34, 0.32],
  [0.92, 0.38, 0.32],
  [0.92, 0.48, 0.36],
  [0.92, 0.34, 0.36],
  [0.92, 0.48, 0.32]],

 [[0.92, 0.54, 0.32],
  [0.96, 0.32, 0.4 ],
  [0.96, 0.42, 0.32],
  [0.96, 0.52, 0.32],
  [0.96, 0.42, 0.32],
  [0.96, 0.42, 0.32],
  [0.96, 0.42, 0.36],
  [0.96, 0.32, 0.4 ],
  [0.86, 0.32, 0.32],
  [0.96, 0.32, 0.32],
  [0.96, 0.32, 0.32],
  [0.96, 0.2, 0.4 ],
  [0.96, 0.42, 0.36]]],
)

print(scores)

[[[0.56 0.68 0.76]
  [0.56 0.68 0.76]
  [0.56 0.68 0.76]
  [0.56 0.68 0.76]
  [0.56 0.68 0.76]
  [0.56 0.68 0.76]
  [0.56 0.68 0.76]
  [0.56 0.68 0.76]
  [0.56 0.68 0.76]
  [0.56 0.68 0.76]
  [0.56 0.68 0.76]
  [0.56 0.68 0.76]
  [0.56 0.68 0.76]]

 [[0.92 0.6  0.36]
  [0.94 0.8  0.36]
  [0.94 0.2  0.32]
  [0.84 0.56 0.36]
  [0.94 0.52 0.32]
  [0.92 0.48 0.32]
  [0.94 0.68 0.32]
  [0.98 0.52 0.36]
  [0.98 0.58 0.32]
  [0.84 0.62 0.32]
  [0.84 0.42 0.28]
  [0.94 0.68 0.36]
  [0.94 0.48 0.32]]

 [[0.92 0.34 0.32]
  [0.92 0.42 0.32]
  [0.92 0.38 0.32]
  [0.92 0.36 0.4 ]
  [0.92 0.34 0.32]
  [0.92 0.38 0.32]
  [1.   0.42 0.32]
  [0.88 0.42 0.32]
  [1.   0.34 0.32]
  [0.92 0.38 0.32]
  [0.92 0.48 0.36]
  [0.92 0.34 0.36]
  [0.92 0.48 0.32]]

 [[0.92 0.54 0.32]
  [0.96 0.32 0.4 ]
  [0.96 0.42 0.32]
  [0.96 0.52 0.32]
  [0.96 0.42 0.32]
  [0.96 0.42 0.32]
  [0.96 0.42 0.36]
  [0.96 0.32 0.4 ]
  [0.86 0.32 0.32]
  [0.96 0.32 0.32]
  [0.96 0.32 0.32]
  [0.96 0.2  0.4 ]
  [0.96 0.42 0.36]]]


# 2 qubit 200 iterations

In [26]:
scores = np.array(
 [[[0.96, 0.58, 0.8 ],
  [0.96, 0.58, 0.8 ],
  [0.96, 0.58, 0.8 ],
  [0.96, 0.58, 0.8 ],
  [0.96, 0.58, 0.8 ],
  [0.96, 0.58, 0.8 ],
  [0.96, 0.58, 0.8 ],
  [0.96, 0.58, 0.8 ],
  [0.96, 0.58, 0.8 ],
  [0.96, 0.58, 0.8 ],
  [0.96, 0.58, 0.8 ],
  [0.96, 0.58, 0.8 ],
  [0.96, 0.58, 0.8 ]],

 [[0.92, 0.86, 0.64],
  [0.94, 0.88, 0.64],
  [0.94, 0.82, 0.72],
  [0.94, 0.76, 0.64],
  [0.94, 0.82, 0.68],
  [0.82, 0.68, 0.72],
  [0.94, 0.78, 0.64],
  [0.98, 0.82, 0.64],
  [0.98, 0.88, 0.72],
  [0.84, 0.82, 0.72],
  [0.94, 0.42, 0.64],
  [0.94, 0.48, 0.64],
  [0.94, 0.88, 0.64]],

 [[0.92, 0.44, 0.64],
  [0.92, 0.2, 0.68],
  [0.92, 0.78, 0.64],
  [1., 0.72, 0.64],
  [0.96, 0.72, 0.68],
  [0.94, 0.72, 0.64],
  [0.98, 0.62, 0.64],
  [0.98, 0.62, 0.56],
  [1., 0.74, 0.68],
  [0.92, 0.48, 0.68],
  [0.92, 0.48, 0.68],
  [1., 0.42, 0.68],
  [0.94, 0.42, 0.72]],

 [[0.98, 0.72, 0.68],
  [0.94, 0.76, 0.68],
  [0.92, 0.46, 0.72],
  [0.92, 0.46, 0.64],
  [0.92, 0.76, 0.68],
  [0.92, 0.76, 0.68],
  [0.92, 0.46, 0.64],
  [0.92, 0.46, 0.68],
  [0.92, 0.46, 0.68],
  [0.92, 0.76, 0.64],
  [0.82, 0.46, 0.72],
  [0.92, 0.46, 0.64],
  [0.92, 0.76, 0.68]]],
)

print(scores)

[[[0.96 0.58 0.8 ]
  [0.96 0.58 0.8 ]
  [0.96 0.58 0.8 ]
  [0.96 0.58 0.8 ]
  [0.96 0.58 0.8 ]
  [0.96 0.58 0.8 ]
  [0.96 0.58 0.8 ]
  [0.96 0.58 0.8 ]
  [0.96 0.58 0.8 ]
  [0.96 0.58 0.8 ]
  [0.96 0.58 0.8 ]
  [0.96 0.58 0.8 ]
  [0.96 0.58 0.8 ]]

 [[0.92 0.86 0.64]
  [0.94 0.88 0.64]
  [0.94 0.82 0.72]
  [0.94 0.76 0.64]
  [0.94 0.82 0.68]
  [0.82 0.68 0.72]
  [0.94 0.78 0.64]
  [0.98 0.82 0.64]
  [0.98 0.88 0.72]
  [0.84 0.82 0.72]
  [0.94 0.42 0.64]
  [0.94 0.48 0.64]
  [0.94 0.88 0.64]]

 [[0.92 0.44 0.64]
  [0.92 0.2  0.68]
  [0.92 0.78 0.64]
  [1.   0.72 0.64]
  [0.96 0.72 0.68]
  [0.94 0.72 0.64]
  [0.98 0.62 0.64]
  [0.98 0.62 0.56]
  [1.   0.74 0.68]
  [0.92 0.48 0.68]
  [0.92 0.48 0.68]
  [1.   0.42 0.68]
  [0.94 0.42 0.72]]

 [[0.98 0.72 0.68]
  [0.94 0.76 0.68]
  [0.92 0.46 0.72]
  [0.92 0.46 0.64]
  [0.92 0.76 0.68]
  [0.92 0.76 0.68]
  [0.92 0.46 0.64]
  [0.92 0.46 0.68]
  [0.92 0.46 0.68]
  [0.92 0.76 0.64]
  [0.82 0.46 0.72]
  [0.92 0.46 0.64]
  [0.92 0.76 0.68]]]


# 2 qubit 400 iterations

In [27]:
scores = np.array(
 [[[0.96, 0.8, 0.84],
  [0.96, 0.8, 0.84],
  [0.96, 0.8, 0.84],
  [0.96, 0.8, 0.84],
  [0.96, 0.8, 0.84],
  [0.96, 0.8, 0.84],
  [0.96, 0.8, 0.84],
  [0.96, 0.8, 0.84],
  [0.96, 0.8, 0.84],
  [0.96, 0.8, 0.84],
  [0.96, 0.8, 0.84],
  [0.96, 0.8, 0.84],
  [0.96, 0.8, 0.84]],

 [[0.92, 0.96, 0.6 ],
  [0.94, 0.78, 0.68],
  [0.94, 0.92, 0.68],
  [0.94, 0.56, 0.72],
  [0.94, 0.82, 0.64],
  [0.92, 0.48, 0.64],
  [0.94, 0.78, 0.68],
  [0.98, 0.62, 0.68],
  [0.98, 0.88, 0.68],
  [0.84, 0.82, 0.68],
  [0.94, 0.82, 0.72],
  [0.84, 0.68, 0.72],
  [0.94, 0.88, 0.64]],

 [[0.92, 0.44, 0.52],
  [0.92, 0.72, 0.64],
  [0.92, 0.8, 0.64],
  [0.92, 0.66, 0.68],
  [0.92, 0.64, 0.68],
  [0.92, 0.48, 0.68],
  [0.92, 0.8, 0.68],
  [1., 0.72, 0.68],
  [0.94, 0.72, 0.68],
  [0.88, 0.42, 0.72],
  [0.88, 0.42, 0.64],
  [0.84, 0.42, 0.68],
  [0.98, 0.42, 0.64]],

 [[0.94, 0.66, 0.68],
  [0.82, 0.46, 0.68],
  [0.92, 0.6, 0.68],
  [0.92, 0.6, 0.68],
  [0.92, 0.76, 0.68],
  [0.92, 0.76, 0.64],
  [0.92, 0.46, 0.64],
  [0.92, 0.6, 0.68],
  [0.92, 0.6, 0.64],
  [0.92, 0.76, 0.72],
  [0.92, 0.46, 0.64],
  [0.92, 0.56, 0.68],
  [0.92, 0.46, 0.64]]],
)

print(scores)

[[[0.96 0.8  0.84]
  [0.96 0.8  0.84]
  [0.96 0.8  0.84]
  [0.96 0.8  0.84]
  [0.96 0.8  0.84]
  [0.96 0.8  0.84]
  [0.96 0.8  0.84]
  [0.96 0.8  0.84]
  [0.96 0.8  0.84]
  [0.96 0.8  0.84]
  [0.96 0.8  0.84]
  [0.96 0.8  0.84]
  [0.96 0.8  0.84]]

 [[0.92 0.96 0.6 ]
  [0.94 0.78 0.68]
  [0.94 0.92 0.68]
  [0.94 0.56 0.72]
  [0.94 0.82 0.64]
  [0.92 0.48 0.64]
  [0.94 0.78 0.68]
  [0.98 0.62 0.68]
  [0.98 0.88 0.68]
  [0.84 0.82 0.68]
  [0.94 0.82 0.72]
  [0.84 0.68 0.72]
  [0.94 0.88 0.64]]

 [[0.92 0.44 0.52]
  [0.92 0.72 0.64]
  [0.92 0.8  0.64]
  [0.92 0.66 0.68]
  [0.92 0.64 0.68]
  [0.92 0.48 0.68]
  [0.92 0.8  0.68]
  [1.   0.72 0.68]
  [0.94 0.72 0.68]
  [0.88 0.42 0.72]
  [0.88 0.42 0.64]
  [0.84 0.42 0.68]
  [0.98 0.42 0.64]]

 [[0.94 0.66 0.68]
  [0.82 0.46 0.68]
  [0.92 0.6  0.68]
  [0.92 0.6  0.68]
  [0.92 0.76 0.68]
  [0.92 0.76 0.64]
  [0.92 0.46 0.64]
  [0.92 0.6  0.68]
  [0.92 0.6  0.64]
  [0.92 0.76 0.72]
  [0.92 0.46 0.64]
  [0.92 0.56 0.68]
  [0.92 0.46 0.64]]]


# 2 qubit 50 iterations - 3 layers

In [28]:
scores = np.array(
 [[[0.76, 0.44, 0.88],
  [0.76, 0.44, 0.88],
  [0.76, 0.44, 0.88],
  [0.76, 0.44, 0.88],
  [0.76, 0.44, 0.88],
  [0.76, 0.44, 0.88],
  [0.76, 0.44, 0.88],
  [0.76, 0.44, 0.88],
  [0.76, 0.44, 0.88],
  [0.76, 0.44, 0.88],
  [0.76, 0.44, 0.88],
  [0.76, 0.44, 0.88],
  [0.76, 0.44, 0.88]],

 [[0.88, 0.64, 0.52],
  [0.68, 0.64, 0.56],
  [0.76, 0.52, 0.48],
  [0.8, 0.64, 0.48],
  [0.72, 0.6, 0.48],
  [0.8, 0.68, 0.48],
  [0.64, 0.52, 0.48],
  [0.76, 0.4, 0.52],
  [0.8, 0.48, 0.52],
  [0.72, 0.64, 0.52],
  [0.68, 0.6, 0.56],
  [0.8, 0.56, 0.52],
  [0.88, 0.48, 0.48]],

 [[0.76, 0.68, 0.88],
  [0.88, 0.56, 0.88],
  [0.84, 0.68, 0.88],
  [0.76, 0.92, 0.92],
  [0.84, 0.68, 0.88],
  [0.72, 0.76, 0.88],
  [0.88, 0.72, 0.84],
  [0.8, 0.96, 0.88],
  [0.92, 0.72, 0.88],
  [0.76, 0.76, 0.8 ],
  [0.76, 0.68, 0.92],
  [0.92, 0.68, 0.92],
  [0.88, 0.72, 0.88]],

 [[0.64, 0.6, 0.48],
  [0.68, 0.56, 0.48],
  [0.72, 0.56, 0.52],
  [0.68, 0.6, 0.48],
  [0.72, 0.48, 0.48],
  [0.72, 0.52, 0.44],
  [0.68, 0.56, 0.44],
  [0.68, 0.6, 0.44],
  [0.72, 0.56, 0.52],
  [0.68, 0.48, 0.44],
  [0.68, 0.52, 0.4 ],
  [0.68, 0.56, 0.52],
  [0.68, 0.64, 0.52]]],
)

print(scores)

[[[0.76 0.44 0.88]
  [0.76 0.44 0.88]
  [0.76 0.44 0.88]
  [0.76 0.44 0.88]
  [0.76 0.44 0.88]
  [0.76 0.44 0.88]
  [0.76 0.44 0.88]
  [0.76 0.44 0.88]
  [0.76 0.44 0.88]
  [0.76 0.44 0.88]
  [0.76 0.44 0.88]
  [0.76 0.44 0.88]
  [0.76 0.44 0.88]]

 [[0.88 0.64 0.52]
  [0.68 0.64 0.56]
  [0.76 0.52 0.48]
  [0.8  0.64 0.48]
  [0.72 0.6  0.48]
  [0.8  0.68 0.48]
  [0.64 0.52 0.48]
  [0.76 0.4  0.52]
  [0.8  0.48 0.52]
  [0.72 0.64 0.52]
  [0.68 0.6  0.56]
  [0.8  0.56 0.52]
  [0.88 0.48 0.48]]

 [[0.76 0.68 0.88]
  [0.88 0.56 0.88]
  [0.84 0.68 0.88]
  [0.76 0.92 0.92]
  [0.84 0.68 0.88]
  [0.72 0.76 0.88]
  [0.88 0.72 0.84]
  [0.8  0.96 0.88]
  [0.92 0.72 0.88]
  [0.76 0.76 0.8 ]
  [0.76 0.68 0.92]
  [0.92 0.68 0.92]
  [0.88 0.72 0.88]]

 [[0.64 0.6  0.48]
  [0.68 0.56 0.48]
  [0.72 0.56 0.52]
  [0.68 0.6  0.48]
  [0.72 0.48 0.48]
  [0.72 0.52 0.44]
  [0.68 0.56 0.44]
  [0.68 0.6  0.44]
  [0.72 0.56 0.52]
  [0.68 0.48 0.44]
  [0.68 0.52 0.4 ]
  [0.68 0.56 0.52]
  [0.68 0.64 0.52]]]


# 2 qubit 200 iterations - 3 layers

In [29]:
scores = np.array(
 [[[0.96, 0.54, 0.8 ],
  [0.96, 0.54, 0.8 ],
  [0.96, 0.54, 0.8 ],
  [0.96, 0.54, 0.8 ],
  [0.96, 0.54, 0.8 ],
  [0.96, 0.54, 0.8 ],
  [0.96, 0.54, 0.8 ],
  [0.96, 0.54, 0.8 ],
  [0.96, 0.54, 0.8 ],
  [0.96, 0.54, 0.8 ],
  [0.96, 0.54, 0.8 ],
  [0.96, 0.54, 0.8 ],
  [0.96, 0.54, 0.8 ]],

 [[0.98, 0.84, 0.8 ],
  [0.98, 0.84, 0.76],
  [0.96, 0.2, 0.76],
  [0.98, 0.64, 0.84],
  [0.92, 0.86, 0.84],
  [0.98, 0.98, 0.76],
  [0.94, 0.62, 0.88],
  [0.96, 0.74, 0.76],
  [0.98, 0.8, 0.84],
  [0.92, 0.94, 0.8 ],
  [0.98, 0.86, 0.88],
  [0.98, 0.6, 0.8 ],
  [0.98, 0.88, 0.72]],

 [[0.96, 0.88, 0.88],
  [0.98, 0.96, 0.84],
  [0.94, 0.98, 0.88],
  [0.96, 0.92, 0.88],
  [0.94, 0.88, 0.88],
  [0.92, 0.86, 0.88],
  [0.98, 0.92, 0.84],
  [0.88, 0.96, 0.92],
  [0.92, 0.92, 0.88],
  [0.96, 0.96, 0.88],
  [0.96, 0.88, 0.88],
  [0.92, 0.98, 0.88],
  [0.98, 0.92, 0.88]],

 [[0.94, 0.76, 0.52],
  [0.98, 0.76, 0.56],
  [0.92, 0.66, 0.6 ],
  [0.98, 0.6, 0.64],
  [0.92, 0.68, 0.64],
  [0.92, 0.72, 0.52],
  [0.98, 0.76, 0.56],
  [0.98, 0.6, 0.6 ],
  [0.92, 0.56, 0.6 ],
  [0.98, 0.58, 0.52],
  [0.98, 0.2, 0.6 ],
  [0.98, 0.66, 0.64],
  [0.98, 0.4, 0.6 ]]],
)

print(scores)

[[[0.96 0.54 0.8 ]
  [0.96 0.54 0.8 ]
  [0.96 0.54 0.8 ]
  [0.96 0.54 0.8 ]
  [0.96 0.54 0.8 ]
  [0.96 0.54 0.8 ]
  [0.96 0.54 0.8 ]
  [0.96 0.54 0.8 ]
  [0.96 0.54 0.8 ]
  [0.96 0.54 0.8 ]
  [0.96 0.54 0.8 ]
  [0.96 0.54 0.8 ]
  [0.96 0.54 0.8 ]]

 [[0.98 0.84 0.8 ]
  [0.98 0.84 0.76]
  [0.96 0.2  0.76]
  [0.98 0.64 0.84]
  [0.92 0.86 0.84]
  [0.98 0.98 0.76]
  [0.94 0.62 0.88]
  [0.96 0.74 0.76]
  [0.98 0.8  0.84]
  [0.92 0.94 0.8 ]
  [0.98 0.86 0.88]
  [0.98 0.6  0.8 ]
  [0.98 0.88 0.72]]

 [[0.96 0.88 0.88]
  [0.98 0.96 0.84]
  [0.94 0.98 0.88]
  [0.96 0.92 0.88]
  [0.94 0.88 0.88]
  [0.92 0.86 0.88]
  [0.98 0.92 0.84]
  [0.88 0.96 0.92]
  [0.92 0.92 0.88]
  [0.96 0.96 0.88]
  [0.96 0.88 0.88]
  [0.92 0.98 0.88]
  [0.98 0.92 0.88]]

 [[0.94 0.76 0.52]
  [0.98 0.76 0.56]
  [0.92 0.66 0.6 ]
  [0.98 0.6  0.64]
  [0.92 0.68 0.64]
  [0.92 0.72 0.52]
  [0.98 0.76 0.56]
  [0.98 0.6  0.6 ]
  [0.92 0.56 0.6 ]
  [0.98 0.58 0.52]
  [0.98 0.2  0.6 ]
  [0.98 0.66 0.64]
  [0.98 0.4  0.6 ]]]


# 2 qubit 400 iterations - 3 layers

In [30]:
scores = np.array(
 [[[0.96, 0.64, 0.84],
  [0.96, 0.64, 0.84],
  [0.96, 0.64, 0.84],
  [0.96, 0.64, 0.84],
  [0.96, 0.64, 0.84],
  [0.96, 0.64, 0.84],
  [0.96, 0.64, 0.84],
  [0.96, 0.64, 0.84],
  [0.96, 0.64, 0.84],
  [0.96, 0.64, 0.84],
  [0.96, 0.64, 0.84],
  [0.96, 0.64, 0.84],
  [0.96, 0.64, 0.84]],

 [[0.98, 0.94, 0.84],
  [0.98, 0.94, 0.92],
  [0.96, 0.82, 0.84],
  [0.98, 0.84, 0.84],
  [0.92, 0.86, 0.8 ],
  [0.98, 0.98, 0.84],
  [0.94, 0.82, 0.76],
  [0.96, 0.94, 0.84],
  [0.98, 0.88, 0.88],
  [0.92, 0.94, 0.92],
  [0.98, 0.6, 0.92],
  [0.98, 0.96, 0.92],
  [0.98, 0.88, 0.88]],

 [[0.96, 0.98, 0.88],
  [0.98, 0.96, 0.92],
  [0.94, 0.98, 0.88],
  [0.96, 0.92, 0.96],
  [0.94, 0.98, 0.96],
  [0.92, 0.96, 0.92],
  [0.98, 0.92, 0.96],
  [0.98, 0.96, 0.84],
  [0.92, 0.82, 0.88],
  [0.96, 0.96, 0.88],
  [0.96, 0.98, 0.88],
  [0.92, 0.98, 0.88],
  [0.98, 0.2, 0.88]],

 [[0.94, 0.76, 0.64],
  [0.98, 0.76, 0.56],
  [0.92, 0.76, 0.56],
  [0.98, 0.76, 0.56],
  [0.92, 0.8, 0.6 ],
  [0.92, 0.62, 0.64],
  [0.98, 0.76, 0.56],
  [0.98, 0.66, 0.56],
  [0.92, 0.6, 0.56],
  [0.98, 0.78, 0.56],
  [0.98, 0.52, 0.52],
  [0.98, 0.76, 0.56],
  [0.98, 0.74, 0.56]]],
)

print(scores)

[[[0.96 0.64 0.84]
  [0.96 0.64 0.84]
  [0.96 0.64 0.84]
  [0.96 0.64 0.84]
  [0.96 0.64 0.84]
  [0.96 0.64 0.84]
  [0.96 0.64 0.84]
  [0.96 0.64 0.84]
  [0.96 0.64 0.84]
  [0.96 0.64 0.84]
  [0.96 0.64 0.84]
  [0.96 0.64 0.84]
  [0.96 0.64 0.84]]

 [[0.98 0.94 0.84]
  [0.98 0.94 0.92]
  [0.96 0.82 0.84]
  [0.98 0.84 0.84]
  [0.92 0.86 0.8 ]
  [0.98 0.98 0.84]
  [0.94 0.82 0.76]
  [0.96 0.94 0.84]
  [0.98 0.88 0.88]
  [0.92 0.94 0.92]
  [0.98 0.6  0.92]
  [0.98 0.96 0.92]
  [0.98 0.88 0.88]]

 [[0.96 0.98 0.88]
  [0.98 0.96 0.92]
  [0.94 0.98 0.88]
  [0.96 0.92 0.96]
  [0.94 0.98 0.96]
  [0.92 0.96 0.92]
  [0.98 0.92 0.96]
  [0.98 0.96 0.84]
  [0.92 0.82 0.88]
  [0.96 0.96 0.88]
  [0.96 0.98 0.88]
  [0.92 0.98 0.88]
  [0.98 0.2  0.88]]

 [[0.94 0.76 0.64]
  [0.98 0.76 0.56]
  [0.92 0.76 0.56]
  [0.98 0.76 0.56]
  [0.92 0.8  0.6 ]
  [0.92 0.62 0.64]
  [0.98 0.76 0.56]
  [0.98 0.66 0.56]
  [0.92 0.6  0.56]
  [0.98 0.78 0.56]
  [0.98 0.52 0.52]
  [0.98 0.76 0.56]
  [0.98 0.74 0.56]]]
