In [1]:
import numpy as np

1 qubit 50 iterations

In [4]:
# scores: [[[0.76 0.68 0.56]\n  [0.76 0.68 0.56]\n  [0.76 0.68 0.56]\n  [0.76 0.68 0.56]\n  [0.76 0.68 0.56]\n  [0.76 0.68 0.56]\n  [0.76 0.68 0.56]\n  [0.76 0.68 0.56]\n  [0.76 0.68 0.56]\n  [0.76 0.68 0.56]\n  [0.76 0.68 0.56]\n  [0.76 0.68 0.56]\n  [0.76 0.68 0.56]]\n\n [[0.84 0.72 0.92]\n  [0.56 0.76 0.84]\n  [0.48 0.72 0.84]\n  [0.76 0.76 0.92]\n  [0.6  0.6  0.88]\n  [0.6  0.76 0.84]\n  [0.36 0.68 0.88]\n  [0.52 0.68 0.84]\n  [0.52 0.64 0.92]\n  [0.52 0.6  0.88]\n  [0.72 0.72 0.92]\n  [0.76 0.76 0.84]\n  [0.76 0.8  0.84]]\n\n [[0.8  0.88 0.92]\n  [0.8  0.68 0.88]\n  [0.76 0.72 0.92]\n  [0.72 0.88 0.84]\n  [0.8  0.48 0.92]\n  [0.72 0.84 0.92]\n  [0.76 0.6  0.88]\n  [0.76 0.88 0.92]\n  [0.72 0.88 0.92]\n  [0.8  0.8  0.92]\n  [0.8  0.44 0.92]\n  [0.76 0.92 0.92]\n  [0.76 0.8  0.92]]]\n
scores = np.array([
 [[0.76, 0.68, 0.56],
  [0.76, 0.68, 0.56],
  [0.76, 0.68, 0.56],
  [0.76, 0.68, 0.56],
  [0.76, 0.68, 0.56],
  [0.76, 0.68, 0.56],
  [0.76, 0.68, 0.56],
  [0.76, 0.68, 0.56],
  [0.76, 0.68, 0.56],
  [0.76, 0.68, 0.56],
  [0.76, 0.68, 0.56],
  [0.76, 0.68, 0.56],
  [0.76, 0.68, 0.56]],

 [[0.84, 0.72, 0.92],
  [0.56, 0.76, 0.84],
  [0.48, 0.72, 0.84],
  [0.76, 0.76, 0.92],
  [0.6, 0.6, 0.88],
  [0.6, 0.76, 0.84],
  [0.36, 0.68, 0.88],
  [0.52, 0.68, 0.84],
  [0.52, 0.64, 0.92],
  [0.52, 0.6, 0.88],
  [0.72, 0.72, 0.92],
  [0.76, 0.76, 0.84],
  [0.76, 0.8, 0.84]],

 [[0.8, 0.88, 0.92],
  [0.8, 0.68, 0.88],
  [0.76, 0.72, 0.92],
  [0.72, 0.88, 0.84],
  [0.8, 0.48, 0.92],
  [0.72, 0.84, 0.92],
  [0.76, 0.6, 0.88],
  [0.76, 0.88, 0.92],
  [0.72, 0.88, 0.92],
  [0.8, 0.8, 0.92],
  [0.8, 0.44, 0.92],
  [0.76, 0.92, 0.92],
  [0.76, 0.8, 0.92]]])

print(scores)

[[[0.76 0.68 0.56]
  [0.76 0.68 0.56]
  [0.76 0.68 0.56]
  [0.76 0.68 0.56]
  [0.76 0.68 0.56]
  [0.76 0.68 0.56]
  [0.76 0.68 0.56]
  [0.76 0.68 0.56]
  [0.76 0.68 0.56]
  [0.76 0.68 0.56]
  [0.76 0.68 0.56]
  [0.76 0.68 0.56]
  [0.76 0.68 0.56]]

 [[0.84 0.72 0.92]
  [0.56 0.76 0.84]
  [0.48 0.72 0.84]
  [0.76 0.76 0.92]
  [0.6  0.6  0.88]
  [0.6  0.76 0.84]
  [0.36 0.68 0.88]
  [0.52 0.68 0.84]
  [0.52 0.64 0.92]
  [0.52 0.6  0.88]
  [0.72 0.72 0.92]
  [0.76 0.76 0.84]
  [0.76 0.8  0.84]]

 [[0.8  0.88 0.92]
  [0.8  0.68 0.88]
  [0.76 0.72 0.92]
  [0.72 0.88 0.84]
  [0.8  0.48 0.92]
  [0.72 0.84 0.92]
  [0.76 0.6  0.88]
  [0.76 0.88 0.92]
  [0.72 0.88 0.92]
  [0.8  0.8  0.92]
  [0.8  0.44 0.92]
  [0.76 0.92 0.92]
  [0.76 0.8  0.92]]]


1 qubit 200 iterations

In [5]:
scores = np.array(
 [[[0.8, 0.52, 0.96],
  [0.8, 0.52, 0.96],
  [0.8, 0.52, 0.96],
  [0.8, 0.52, 0.96],
  [0.8, 0.52, 0.96],
  [0.8, 0.52, 0.96],
  [0.8, 0.52, 0.96],
  [0.8, 0.52, 0.96],
  [0.8, 0.52, 0.96],
  [0.8, 0.52, 0.96],
  [0.8, 0.52, 0.96],
  [0.8, 0.52, 0.96],
  [0.8, 0.52, 0.96]],

 [[0.44, 0.8, 0.84],
  [0.76, 0.72, 0.92],
  [0.6, 0.68, 0.88],
  [0.4, 0.68, 0.84],
  [0.44, 0.68, 0.84],
  [0.52, 0.68, 0.92],
  [0.8, 0.76, 0.92],
  [0.44, 0.72, 0.84],
  [0.4, 0.8, 0.84],
  [0.6, 0.76, 0.88],
  [0.64, 0.68, 0.92],
  [0.36, 0.68, 0.84],
  [0.56, 0.76, 0.84]],

 [[0.8, 0.6, 0.92],
  [0.84, 0.72, 0.96],
  [0.8, 0.8, 0.92],
  [0.84, 0.84, 0.96],
  [0.8, 0.8, 0.96],
  [0.84, 0.8, 0.96],
  [0.84, 0.92, 0.92],
  [0.84, 0.92, 0.88],
  [0.84, 0.44, 0.92],
  [0.8, 0.8, 0.92],
  [0.8, 0.8, 0.92],
  [0.84, 0.44, 0.92],
  [0.8, 0.88, 0.96]]]
)

print(scores)

[[[0.8  0.52 0.96]
  [0.8  0.52 0.96]
  [0.8  0.52 0.96]
  [0.8  0.52 0.96]
  [0.8  0.52 0.96]
  [0.8  0.52 0.96]
  [0.8  0.52 0.96]
  [0.8  0.52 0.96]
  [0.8  0.52 0.96]
  [0.8  0.52 0.96]
  [0.8  0.52 0.96]
  [0.8  0.52 0.96]
  [0.8  0.52 0.96]]

 [[0.44 0.8  0.84]
  [0.76 0.72 0.92]
  [0.6  0.68 0.88]
  [0.4  0.68 0.84]
  [0.44 0.68 0.84]
  [0.52 0.68 0.92]
  [0.8  0.76 0.92]
  [0.44 0.72 0.84]
  [0.4  0.8  0.84]
  [0.6  0.76 0.88]
  [0.64 0.68 0.92]
  [0.36 0.68 0.84]
  [0.56 0.76 0.84]]

 [[0.8  0.6  0.92]
  [0.84 0.72 0.96]
  [0.8  0.8  0.92]
  [0.84 0.84 0.96]
  [0.8  0.8  0.96]
  [0.84 0.8  0.96]
  [0.84 0.92 0.92]
  [0.84 0.92 0.88]
  [0.84 0.44 0.92]
  [0.8  0.8  0.92]
  [0.8  0.8  0.92]
  [0.84 0.44 0.92]
  [0.8  0.88 0.96]]]


1 qubit 400 iterations

In [ ]:
scores = np.array(
    
)

print(scores)