## Angle encoding


In [1]:
import pennylane as qml
from pennylane import numpy as np
from pennylane.templates.embeddings import AngleEmbedding

dev1 = qml.device('default.qubit', wires=2)
dev2 = qml.device('default.qubit', wires=2)

@qml.qnode(dev1)
def circuit1(data, probs=False):
    # for i in range(2):
    #     qml.Hadamard(i)
    for i in range(len(data)):
        AngleEmbedding(features=data[i], wires=range(2), rotation='Y')
    if probs:
      return  qml.probs(wires=range(2))
    return  qml.state()
    

@qml.qnode(dev2)
def circuit2(data, probs=False):
    # for i in range(2):
    #     qml.Hadamard(i)
    for i in range(len(data)):
        qml.RY(data[i][0], wires=0) # input feature 1
        qml.RY(data[i][1], wires=1) # input feature 2
    if probs:
      return  qml.probs(wires=range(2))
    return  qml.state()
    

x = 1.25
y = 2.3
data = np.array([[x, y]])

print(circuit1(data))
print()
print(circuit1.draw(show_all_wires=True))
print("probs:")
print(circuit1(data, True))

print("------------")
print(circuit2(data))
print()
print(circuit2.draw(show_all_wires=True))
print("probs:")
probs = circuit2(data, True)
print(circuit2(data, True))
print(np.sum(probs))


[0.33126825+0.j 0.74021789+0.j 0.23900489+0.j 0.53405569+0.j]

 0: ──RY(1.25)──╭┤ State 
 1: ──RY(2.3)───╰┤ State 

probs:
[0.10973865 0.54792253 0.05712334 0.28521548]
------------
[0.33126825+0.j 0.74021789+0.j 0.23900489+0.j 0.53405569+0.j]

 0: ──RY(1.25)──╭┤ State 
 1: ──RY(2.3)───╰┤ State 

probs:
[0.10973865 0.54792253 0.05712334 0.28521548]
1.0


/Users/phuber/opt/anaconda3/lib/python3.9/site-packages/pennylane/qnode.py:838: UserWarning: The QNode.draw method has been deprecated. Please use the qml.draw(qnode)(*args) function instead.
  warnings.warn(


In [2]:
dev3 = qml.device('default.qubit', wires=2)

@qml.qnode(dev3)
def circuit3(data, probs=False):
    for i in range(len(data)):
        AngleEmbedding(features=data[i], wires=range(2), rotation='Y')
    if probs:
      return  qml.probs(wires=range(2))
    return  qml.state()
    

x = 10.25
y = 20.3
x_scaled = 1.25
y_scaled = 2.3
data = np.array([[x, y]])

print(circuit3(data))
print()
print(circuit3.draw(show_all_wires=True))
print("probs:")
print(circuit3(data, True))

[-0.30009115+0.j -0.26598567+0.j  0.68554814+0.j  0.60763531+0.j]

 0: ──RY(10.2)──╭┤ State 
 1: ──RY(20.3)──╰┤ State 

probs:
[0.0900547  0.07074837 0.46997626 0.36922067]


In [4]:

# Test rotation gate vs singe gates state
dev4 = qml.device('default.qubit', wires=1)
dev5 = qml.device('default.qubit', wires=1)

@qml.qnode(dev4)
def circuit4(data, probs=False):
    qml.Rot(data[0], data[1], data[2], wires=0)
    if probs:
      return  qml.probs(wires=range(1))
    return  qml.state()

data = np.array([1.2, 0.23, 0.01])

print(circuit4(data))
print()
print(circuit4.draw(show_all_wires=True))
print("probs:")
print(circuit4(data, True))


@qml.qnode(dev5)
def circuit5(data, probs=False):
    qml.RZ(data[0], wires=0) 
    qml.RY(data[1], wires=0) 
    qml.RZ(data[2], wires=0) 
    if probs:
      return  qml.probs(wires=range(1))
    return  qml.state()

print(circuit5(data))
print()
print(circuit5.draw(show_all_wires=True))
print("probs:")
print(circuit5(data, True))

[0.81706929-0.56500528j 0.0950273 -0.06431652j]

 0: ──Rot(1.2, 0.23, 0.01)──┤ State 

probs:
[0.9868332 0.0131668]
[0.81706929-0.56500528j 0.0950273 -0.06431652j]

 0: ──RZ(1.2)──RY(0.23)──RZ(0.01)──┤ State 

probs:
[0.9868332 0.0131668]
